### ISSUE TITLE
Additional Button Style 

### ISSUE THREAD

**Issue by mat10tng** [factn/mutualaidworld_frontend#28]
![image](https://user-images.githubusercontent.com/3273671/77285816-336dfe80-6cd2-11ea-87db-bb7d9b2b50d5.png)
![image](https://user-images.githubusercontent.com/3273671/77285841-441e7480-6cd2-11ea-9afb-973c8b3b9448.png)

create color, bgcolor (we are following material design component api) as props that will override any of the button preset.

**Comment by ruchijn** [comment]
I am working on it.

**Comment by zerinoid** [comment]
@ruchijn ring me if you need any help

**Comment by mat10tng** [comment]
Sorry, We still need this to get done with.
