### ISSUE TITLE
MakeARequestPage //Terrence

### ISSUE THREAD

**Issue by mat10tng** [factn/mutualaidworld_frontend#30]
![image](https://user-images.githubusercontent.com/3273671/77300426-4d1d3f00-6cee-11ea-8476-f8039730f2d0.png)

Ignore the appbar, and color, go with hardcoded if you like for now, we will input theme later
Making sure you are using existing component, if it not existing, you can ignore it for now
maxwidth of container to 600px!

app/page/RequestCreate
> RequestCreate.js
> RequestCreate.style.js
> RequestCreate.test.js
> index.js  // export default here

**Comment by considine** [comment]
Have we decided on the payment service? Stripe?

**Comment by mat10tng** [comment]
We are not going to work with payment at this time.

**Comment by thedma04** [comment]
@mat10tng can you assign this to me
