### ISSUE TITLE
Create new account page // Ruchi Rain

### ISSUE THREAD

**Issue by mat10tng** [factn/mutualaidworld_frontend#31]
![image](https://user-images.githubusercontent.com/3273671/77301995-e4839180-6cf0-11ea-94d1-e1b94f319e9b.png)

Ignore the appbar, and color, go with hardcoded if you like for now, we will input theme later
Making sure you are using existing component, if it not existing, you can ignore it for now
maxwidth of container to 600px!

app/page/AccountCreate

AccountCreate.js
AccountCreate.style.js
AccountCreate.test.js
index.js // export default here

**Comment by Raf-Batista** [comment]
I can take this if no one is on it already.

**Comment by mat10tng** [comment]
Hi, its in progress already, you can see it in the label

**Comment by Raf-Batista** [comment]
Oops, did't notice it. Good thing I came back here. I was just about to get started.
