### ISSUE TITLE
Sign-up screen [In Progress by Terrence]

### ISSUE THREAD

**Issue by mat10tng** [factn/mutualaidworld_frontend#6]
![image](https://user-images.githubusercontent.com/3273671/77228454-e847d480-6b87-11ea-99eb-f759df125b64.png)
Link to Figma design: [Link](https://www.figma.com/file/v5HdxDsvO2NzMuZU6CArzF/Corona-Donor-Designs-in-progress?node-id=170%3A255)
Please refer to figma design as it has changed! The picture uploaded are only used as a point of ref.

**Comment by CSumm** [comment]
@mat10tng are you doing this issue, or is it possible for me to take up the job?

**Comment by mat10tng** [comment]
Hi, please check with @Terrence  in slack channel, He said he was ready to take it up. But I have no clue. I will try to get some more issues going
