### ISSUE TITLE
Signup -> login flow // Azmain Amin

### ISSUE THREAD

**Issue by mat10tng** [factn/mutualaidworld_frontend#61]
So we can have a profile yo

**Comment by azmainamin** [comment]
@mat10tng I believe we can close this now. See: 
1. https://github.com/factn/mutualaidworld_frontend/pull/72
2. https://github.com/factn/mutualaidworld_frontend/pull/74

**Comment by pedro-surf** [comment]
When I enter the code I received, I got redirected to a broken route.

[#72]
