### ISSUE TITLE
Mission List Style

### ISSUE THREAD

**Issue by mat10tng** [factn/mutualaidworld_frontend#64]
Very basic styling, we would like it to look decent, with a placeholder of image, and properly field. Do contact designer if you feel like you need. Update me with status so I know where you are at

**Comment by mat10tng** [comment]
![image](https://user-images.githubusercontent.com/3273671/77563215-4266d380-6ec1-11ea-94b4-ffc1ac7e4e37.png)

**Comment by thirdeyeclub** [comment]
I am working on this, but i need to figure out what the data from the backend is before I can finish
